/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baseproject_ndk_ImageLosslessCompress */

#ifndef _Included_com_baseproject_ndk_ImageLosslessCompress
#define _Included_com_baseproject_ndk_ImageLosslessCompress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baseproject_ndk_ImageLosslessCompress
 * Method:    compressImage
 * Signature: (Landroid/graphics/Bitmap;III[BZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pince_image_1lossless_1compression_ImageLosslessCompress_compressImage
  (JNIEnv *, jclass, jobject, jint, jint, jint, jbyteArray, jboolean);

char *jstringToChar(JNIEnv *pEnv, jbyteArray pArray);

#ifdef __cplusplus
}
#endif
#endif
